version: '3'
services:
  acme.sh:
    image: neilpang/acme.sh
    container_name: acme.sh
    restart: always
    command: daemon
    environment:
      - Ali_Key=xxxxx
      - Ali_Secret=xxxxx
    volumes:
      - ./ssl/:/acme.sh
    network_mode: host
