version: '3'
services:
  acme.sh:
    image: neilpang/acme.sh
    container_name: acme.sh
    restart: always
    command: daemon
    env_file:
      - .env
    volumes:
      - ./ssl/:/acme.sh
    network_mode: host
