version: '3'
services:
  ng:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/www/:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/nginx.conf
