version: '3'
services:
  ng:
    image: nginx
    restart: always
    container_name: nginx
    ports:
      - ${NG_HTTP:-80}:80
      - ${NG_HTTPS:-443}:443
    volumes:
      - ${STATIC_PATH:-./www}/:/usr/share/nginx/html/
      - ./conf/${NG_ENV:-dev}.conf:/etc/nginx/conf.d/tmp.ng
      - ./ssl:/usr/share/nginx/html/ssl/
    environment:
      APP_PORT: ${APP_PORT:-3000}
      APP_NAME: ${APP_NAME:-app}
    command: /bin/bash -c "envsubst '$$APP_PORT $$APP_NAME' < /etc/nginx/conf.d/tmp.ng > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

