version: '3'
services:
  ng:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/www/:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/temp.conf
     environment:
      APP_PORT: 3000
      APP_NAME: name
    command: /bin/bash -c "envsubst '$$APP_PORT $$APP_NAME' < /etc/nginx/conf.d/temp.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

