version: '3'
services:
  ng:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/www/blog:/usr/share/nginx/html/blog
      - /data/www/ssl:/usr/share/nginx/html/ssl
      - ./nginx.conf:/etc/nginx/nginx.conf
